version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\CoreFNBT" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\CoreFNBT.Serialization" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\CoreFNBT.Test" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\CoreFNBT" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\CoreFNBT.Serialization" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
test_script:
- dotnet test "src\CoreFNBT.Test" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
deploy:
- provider: NuGet
  api_key:
    secure: xOnejg7iw7MjF2DdCNi3fqauM8R5P15xmwa8zD7nFNKM/avGsGDwXqsPTRbvEMx9
  skip_symbols: false
cache:
- '%USERPROFILE%\.nuget\packages'


version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Best practice (Windows line endings different to Unix/Linux)
  - cmd: git config --global core.autocrlf true
install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.6.0/nuget.exe
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/CoreFNBT/CoreFNBT.csproj --verbosity m
  - cmd: dotnet restore ./src/CoreFNBT.Serialization/CoreFNBT.Serialization.csproj --verbosity m
  - cmd: dotnet restore ./src/CoreFNBT.Test/CoreFNBT.Test.csproj --verbosity m
build_script:
    - cmd: dotnet build ./CoreFNBT/CoreFNBT.csproj -c Release
    - cmd: dotnet pack -c Release /p:PackageVersion=1.0.{build} 
    - cmd: dotnet build ./CoreFNBT.Serialization/CoreFNBT.Serialization.csproj -c Release
    - cmd: dotnet pack -c Release /p:PackageVersion=1.0.{build} 
artifacts:
- path: ./Threenine.Data/bin/Release/*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: xOnejg7iw7MjF2DdCNi3fqauM8R5P15xmwa8zD7nFNKM/avGsGDwXqsPTRbvEMx9
  skip_symbols: true
